<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>Transformalize.Provider.Mail</AssemblyName>
    <RootNamespace>Transformalize.Providers.Mail</RootNamespace>
    <Version>1.1.0</Version>
    <FileVersion>1.1.0</FileVersion>
    <AssemblyVersion>1.1.0</AssemblyVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.16.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../Transformalize/Transformalize.csproj" />
  </ItemGroup>
</Project>
