nuget pack Compatibility\Transformalize\Transformalize.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Pipeline.Logging.NLog\Transformalize.Logging.NLog.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Providers\Ado\Transformalize.Provider.Ado.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Providers\Elastic\Transformalize.Provider.Elastic.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Providers\Excel\Transformalize.Provider.Excel.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Providers\OpenXml\Transformalize.Provider.OpenXml.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Providers\File\Transformalize.Provider.File.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Providers\Lucene\Transformalize.Provider.Lucene.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Providers\MySql\Transformalize.Provider.MySql.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Providers\PostgreSql\Transformalize.Provider.PostgreSql.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Providers\Solr\Transformalize.Provider.Solr.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Providers\SQLite\Transformalize.Provider.SQLite.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Providers\SqlServer\Transformalize.Provider.SqlServer.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Providers\SqlCe\Transformalize.Provider.SqlCe.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Providers\Web\Transformalize.Provider.Web.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Providers\Console\Transformalize.Provider.Console.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Providers\Trace\Transformalize.Provider.Trace.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Pipeline.Scheduler.Quartz\Transformalize.Scheduler.Quartz.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transforms\Humanizer\Transformalize.Transform.Humanizer.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transforms\Jint\Transformalize.Transform.Jint.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transforms\JavaScript\Transformalize.Transform.JavaScript.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transforms\Globalization\Transformalize.Transform.Globalization.nuspec -OutputDirectory "c:\temp\modules"


