<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
      <TargetFramework>netstandard2.0</TargetFramework>
      <RootNamespace>Transformalize.Transforms.Geography</RootNamespace>
      <AssemblyName>Transformalize.Transform.Geography</AssemblyName>
      <Version>1.4.4</Version>
      <FileVersion>1.4.4</FileVersion>
      <AssemblyVersion>1.4.4</AssemblyVersion>
   </PropertyGroup>

   <ItemGroup>
     <PackageReference Include="Geolocation" Version="1.2.1" />
     <PackageReference Include="NGeoHash" Version="1.2.0" />
   </ItemGroup>

   <ItemGroup>
      <ProjectReference Include="..\..\Transformalize\Transformalize.csproj" />
   </ItemGroup>

</Project>
