<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Transformalize.Providers.Lucene</RootNamespace>
    <AssemblyName>Transformalize.Provider.Lucene</AssemblyName>
    <Version>1.4.3</Version>
    <FileVersion>1.4.3</FileVersion>
    <AssemblyVersion>1.4.3</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lucene.Net" Version="4.8.0-beta00017" />
    <PackageReference Include="Lucene.Net.Grouping" Version="4.8.0-beta00017" />
    <PackageReference Include="Lucene.Net.QueryParser" Version="4.8.0-beta00017" />
    <ProjectReference Include="../../../Transformalize/Transformalize.csproj" />
  </ItemGroup>

</Project>
