nuget pack Transformalize.nuspec -OutputDirectory "c:\temp\modules"

REM CONTAINERS
nuget pack Transformalize.Container.Autofac.nuspec -OutputDirectory "c:\temp\modules"

REM REM MISC
nuget pack Transformalize.Logging.NLog.nuspec -OutputDirectory "c:\temp\modules"

REM PROVIDERS
nuget pack Transformalize.Provider.Bogus.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.Bogus.Autofac.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.Ado.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.Ado.Autofac.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.OpenXml.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.Kml.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.File.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.File.Autofac.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.CsvHelper.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.CsvHelper.Autofac.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.Console.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.Console.Autofac.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.Mail.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.Mail.Autofac.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.Trace.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.SqlServer.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.SqlServer.Autofac.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.PostgreSql.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.PostgreSql.Autofac.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.MySql.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.MySql.Autofac.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.Sqlite.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.Sqlite.Autofac.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.GeoJson.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.GeoJson.Autofac.nuspec -OutputDirectory "c:\temp\modules"

REM TRANSFORMS
nuget pack Transformalize.Transform.Jint.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Transform.Jint.Autofac.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Transform.Humanizer.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Transform.Humanizer.Autofac.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Validate.Jint.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Validate.Jint.Autofac.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Transform.Ado.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Transform.Ado.Autofac.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Transform.Globalization.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Transform.Compression.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Transform.Geography.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Transform.Xml.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Transform.Fluid.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Transform.Fluid.Autofac.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Transform.GoogleMaps.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Transform.GoogleMaps.Autofac.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Transform.LambdaParser.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Transform.LambdaParser.Autofac.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.Razor.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Provider.Razor.Autofac.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Transform.Razor.nuspec -OutputDirectory "c:\temp\modules"
nuget pack Transformalize.Transform.Razor.Autofac.nuspec -OutputDirectory "c:\temp\modules"
