//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transformalize.Libs.EnterpriseLibrary.Common.Configuration {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DesignResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesignResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.EnterpriseLibrary.Common.Configuration.DesignResources", typeof(DesignResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Application Settings.
        /// </summary>
        internal static string AddApplicationSettingsTitle {
            get {
                return ResourceManager.GetString("AddApplicationSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Configuration Settings.
        /// </summary>
        internal static string AddConfigurationSourcesTitle {
            get {
                return ResourceManager.GetString("AddConfigurationSourcesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Instrumentation Settings.
        /// </summary>
        internal static string AddInstrumentationSettingsTitle {
            get {
                return ResourceManager.GetString("AddInstrumentationSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings .
        /// </summary>
        internal static string AppSettingsSectionMetadataDescription {
            get {
                return ResourceManager.GetString("AppSettingsSectionMetadataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        internal static string AppSettingsSectionMetadataDisplayName {
            get {
                return ResourceManager.GetString("AppSettingsSectionMetadataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string CategoryGeneral {
            get {
                return ResourceManager.GetString("CategoryGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization.
        /// </summary>
        internal static string CategoryLocalization {
            get {
                return ResourceManager.GetString("CategoryLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (name).
        /// </summary>
        internal static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A manageability provider for a configuration element..
        /// </summary>
        internal static string ConfigurationElementManageabilityProviderDataDescription {
            get {
                return ResourceManager.GetString("ConfigurationElementManageabilityProviderDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Element Manageability Provider.
        /// </summary>
        internal static string ConfigurationElementManageabilityProviderDataDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationElementManageabilityProviderDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Configuration Element Manageability Provider..
        /// </summary>
        internal static string ConfigurationElementManageabilityProviderDataNameDescription {
            get {
                return ResourceManager.GetString("ConfigurationElementManageabilityProviderDataNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ConfigurationElementManageabilityProviderDataNameDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationElementManageabilityProviderDataNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type that is managed by the manageability provider..
        /// </summary>
        internal static string ConfigurationElementManageabilityProviderDataTargetTypeDescription {
            get {
                return ResourceManager.GetString("ConfigurationElementManageabilityProviderDataTargetTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Type.
        /// </summary>
        internal static string ConfigurationElementManageabilityProviderDataTargetTypeDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationElementManageabilityProviderDataTargetTypeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified type name of the Configuration Element Manageability Provider..
        /// </summary>
        internal static string ConfigurationElementManageabilityProviderDataTypeNameDescription {
            get {
                return ResourceManager.GetString("ConfigurationElementManageabilityProviderDataTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ConfigurationElementManageabilityProviderDataTypeNameDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationElementManageabilityProviderDataTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A manageability provider for a configuration section..
        /// </summary>
        internal static string ConfigurationSectionManageabilityProviderDataDescription {
            get {
                return ResourceManager.GetString("ConfigurationSectionManageabilityProviderDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Section Manageability Provider.
        /// </summary>
        internal static string ConfigurationSectionManageabilityProviderDataDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationSectionManageabilityProviderDataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collection of Manageability Providers that the receiver might require to provide 
        ///manageability to configuration elements..
        /// </summary>
        internal static string ConfigurationSectionManageabilityProviderDataManageabilityProvidersDescription {
            get {
                return ResourceManager.GetString("ConfigurationSectionManageabilityProviderDataManageabilityProvidersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manageability Providers.
        /// </summary>
        internal static string ConfigurationSectionManageabilityProviderDataManageabilityProvidersDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationSectionManageabilityProviderDataManageabilityProvidersDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Manageability Provider..
        /// </summary>
        internal static string ConfigurationSectionManageabilityProviderDataNameDescription {
            get {
                return ResourceManager.GetString("ConfigurationSectionManageabilityProviderDataNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ConfigurationSectionManageabilityProviderDataNameDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationSectionManageabilityProviderDataNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified type name of the Manageability Provider..
        /// </summary>
        internal static string ConfigurationSectionManageabilityProviderDataTypeNameDescription {
            get {
                return ResourceManager.GetString("ConfigurationSectionManageabilityProviderDataTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ConfigurationSectionManageabilityProviderDataTypeNameDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationSectionManageabilityProviderDataTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element that represents a configuration source ..
        /// </summary>
        internal static string ConfigurationSourceElementDescription {
            get {
                return ResourceManager.GetString("ConfigurationSourceElementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element that contains configurtain information..
        /// </summary>
        internal static string ConfigurationSourceElementDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationSourceElementDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Configuration Source Element..
        /// </summary>
        internal static string ConfigurationSourceElementNameDescription {
            get {
                return ResourceManager.GetString("ConfigurationSourceElementNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ConfigurationSourceElementNameDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationSourceElementNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified type name of the Configuration Source Element..
        /// </summary>
        internal static string ConfigurationSourceElementTypeNameDescription {
            get {
                return ResourceManager.GetString("ConfigurationSourceElementTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ConfigurationSourceElementTypeNameDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationSourceElementTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration settings that determine the sources of configuration information for an application..
        /// </summary>
        internal static string ConfigurationSourceSectionDescription {
            get {
                return ResourceManager.GetString("ConfigurationSourceSectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Sources.
        /// </summary>
        internal static string ConfigurationSourceSectionDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationSourceSectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Configuration Source containing the section that this Redirected Section will override..
        /// </summary>
        internal static string ConfigurationSourceSectionParentSourceDescription {
            get {
                return ResourceManager.GetString("ConfigurationSourceSectionParentSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Source.
        /// </summary>
        internal static string ConfigurationSourceSectionParentSourceDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationSourceSectionParentSourceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of Redirected Sections for this application configuration..
        /// </summary>
        internal static string ConfigurationSourceSectionRedirectedSectionsDescription {
            get {
                return ResourceManager.GetString("ConfigurationSourceSectionRedirectedSectionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirected Sections.
        /// </summary>
        internal static string ConfigurationSourceSectionRedirectedSectionsDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationSourceSectionRedirectedSectionsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the default Configuration Source..
        /// </summary>
        internal static string ConfigurationSourceSectionSelectedSourceDescription {
            get {
                return ResourceManager.GetString("ConfigurationSourceSectionSelectedSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Source.
        /// </summary>
        internal static string ConfigurationSourceSectionSelectedSourceDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationSourceSectionSelectedSourceDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of defined configuration sources..
        /// </summary>
        internal static string ConfigurationSourceSectionSourcesDescription {
            get {
                return ResourceManager.GetString("ConfigurationSourceSectionSourcesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        internal static string ConfigurationSourceSectionSourcesDisplayName {
            get {
                return ResourceManager.GetString("ConfigurationSourceSectionSourcesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Configuration Source that reads configuration information from a disk file. 
        ///The file must contain XML data in the standard .NET configuration format..
        /// </summary>
        internal static string FileConfigurationSourceElementDescription {
            get {
                return ResourceManager.GetString("FileConfigurationSourceElementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File-based Configuration Source.
        /// </summary>
        internal static string FileConfigurationSourceElementDisplayName {
            get {
                return ResourceManager.GetString("FileConfigurationSourceElementDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full path and name of the configuration file..
        /// </summary>
        internal static string FileConfigurationSourceElementFilePathDescription {
            get {
                return ResourceManager.GetString("FileConfigurationSourceElementFilePathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        internal static string FileConfigurationSourceElementFilePathDisplayName {
            get {
                return ResourceManager.GetString("FileConfigurationSourceElementFilePathDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration files (*.config)|*.config|All Files (*.*)|*.*.
        /// </summary>
        internal static string FileConfigurationSourceElementFilePathFilter {
            get {
                return ResourceManager.GetString("FileConfigurationSourceElementFilePathFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the File-based Configuration Source..
        /// </summary>
        internal static string FileConfigurationSourceElementNameDescription {
            get {
                return ResourceManager.GetString("FileConfigurationSourceElementNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FileConfigurationSourceElementNameDisplayName {
            get {
                return ResourceManager.GetString("FileConfigurationSourceElementNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified type name of the File-based Configuration Source..
        /// </summary>
        internal static string FileConfigurationSourceElementTypeNameDescription {
            get {
                return ResourceManager.GetString("FileConfigurationSourceElementTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string FileConfigurationSourceElementTypeNameDisplayName {
            get {
                return ResourceManager.GetString("FileConfigurationSourceElementTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unique name for the Application Instance to be used by the Instrumentation providers..
        /// </summary>
        internal static string InstrumentationConfigurationSectionApplicationInstanceNameDescription {
            get {
                return ResourceManager.GetString("InstrumentationConfigurationSectionApplicationInstanceNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Instance Name.
        /// </summary>
        internal static string InstrumentationConfigurationSectionApplicationInstanceNameDisplayName {
            get {
                return ResourceManager.GetString("InstrumentationConfigurationSectionApplicationInstanceNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration settings for Instrumentation for the entire application..
        /// </summary>
        internal static string InstrumentationConfigurationSectionDescription {
            get {
                return ResourceManager.GetString("InstrumentationConfigurationSectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrumentation Settings.
        /// </summary>
        internal static string InstrumentationConfigurationSectionDisplayName {
            get {
                return ResourceManager.GetString("InstrumentationConfigurationSectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if logging to Windows Event Log will take place when instrumented 
        ///events occur within Enterprise Library..
        /// </summary>
        internal static string InstrumentationConfigurationSectionEventLoggingEnabledDescription {
            get {
                return ResourceManager.GetString("InstrumentationConfigurationSectionEventLoggingEnabledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Logging Enabled.
        /// </summary>
        internal static string InstrumentationConfigurationSectionEventLoggingEnabledDisplayName {
            get {
                return ResourceManager.GetString("InstrumentationConfigurationSectionEventLoggingEnabledDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if the Enterprise Library Performance Counters will be exposed and updated 
        ///when instrumented events occur within Enterprise Library..
        /// </summary>
        internal static string InstrumentationConfigurationSectionPerformanceCountersEnabledDescription {
            get {
                return ResourceManager.GetString("InstrumentationConfigurationSectionPerformanceCountersEnabledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Counters Enabled.
        /// </summary>
        internal static string InstrumentationConfigurationSectionPerformanceCountersEnabledDisplayName {
            get {
                return ResourceManager.GetString("InstrumentationConfigurationSectionPerformanceCountersEnabledDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string KeyValueConfigurationCollectionMetadataDescription {
            get {
                return ResourceManager.GetString("KeyValueConfigurationCollectionMetadataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string KeyValueConfigurationCollectionMetadataDisplayName {
            get {
                return ResourceManager.GetString("KeyValueConfigurationCollectionMetadataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A custom application settings, such as file paths or XML Web service URLs..
        /// </summary>
        internal static string KeyValueConfigurationElementMetadataDescription {
            get {
                return ResourceManager.GetString("KeyValueConfigurationElementMetadataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string KeyValueConfigurationElementMetadataDisplayName {
            get {
                return ResourceManager.GetString("KeyValueConfigurationElementMetadataDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string KeyValueConfigurationElementMetadataKeyDescription {
            get {
                return ResourceManager.GetString("KeyValueConfigurationElementMetadataKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string KeyValueConfigurationElementMetadataKeyDisplayName {
            get {
                return ResourceManager.GetString("KeyValueConfigurationElementMetadataKeyDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string KeyValueConfigurationElementMetadataValueDescription {
            get {
                return ResourceManager.GetString("KeyValueConfigurationElementMetadataValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string KeyValueConfigurationElementMetadataValueDisplayName {
            get {
                return ResourceManager.GetString("KeyValueConfigurationElementMetadataValueDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the application. 
        ///This used to determine the Registry path for the configuration information. 
        ///This value is required..
        /// </summary>
        internal static string ManageableConfigurationSourceElementApplicationNameDescription {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementApplicationNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name.
        /// </summary>
        internal static string ManageableConfigurationSourceElementApplicationNameDisplayName {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementApplicationNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of registered types necessary to provide manageability by the configuration source..
        /// </summary>
        internal static string ManageableConfigurationSourceElementConfigurationManageabilityProvidersDescription {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementConfigurationManageabilityProvidersDescriptio" +
                        "n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Manageability Providers.
        /// </summary>
        internal static string ManageableConfigurationSourceElementConfigurationManageabilityProvidersDisplayName {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementConfigurationManageabilityProvidersDisplayNam" +
                        "e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A configuration source that integrates with Group Policy to apply domain-wide or 
        ///local machine policy overrides to provide centralized configuration management capabilities..
        /// </summary>
        internal static string ManageableConfigurationSourceElementDescription {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manageable Configuration Source.
        /// </summary>
        internal static string ManageableConfigurationSourceElementDisplayName {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if the configuration source will take account of domain-wide or 
        ///local machine policy overrides configured in the Registry through Group Policy settings..
        /// </summary>
        internal static string ManageableConfigurationSourceElementEnableGroupPoliciesDescription {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementEnableGroupPoliciesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Policy Enabled.
        /// </summary>
        internal static string ManageableConfigurationSourceElementEnableGroupPoliciesDisplayName {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementEnableGroupPoliciesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full path and name of the configuration file..
        /// </summary>
        internal static string ManageableConfigurationSourceElementFilePathDescription {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementFilePathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        internal static string ManageableConfigurationSourceElementFilePathDisplayName {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementFilePathDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Manageable Configuration Source..
        /// </summary>
        internal static string ManageableConfigurationSourceElementNameDescription {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ManageableConfigurationSourceElementNameDisplayName {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified type name of the Manageable Configuration Source..
        /// </summary>
        internal static string ManageableConfigurationSourceElementTypeNameDescription {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ManageableConfigurationSourceElementTypeNameDisplayName {
            get {
                return ResourceManager.GetString("ManageableConfigurationSourceElementTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A configuration element in a collection that is keyed by the name..
        /// </summary>
        internal static string NamedConfigurationElementDescription {
            get {
                return ResourceManager.GetString("NamedConfigurationElementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named Configuration Element.
        /// </summary>
        internal static string NamedConfigurationElementDisplayName {
            get {
                return ResourceManager.GetString("NamedConfigurationElementDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name used to identify this item..
        /// </summary>
        internal static string NamedConfigurationElementNameDescription {
            get {
                return ResourceManager.GetString("NamedConfigurationElementNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NamedConfigurationElementNameDisplayName {
            get {
                return ResourceManager.GetString("NamedConfigurationElementNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collection of Named Configuration elements..
        /// </summary>
        internal static string NamedElementCollectionDescription {
            get {
                return ResourceManager.GetString("NamedElementCollectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named Element Collection.
        /// </summary>
        internal static string NamedElementCollectionDisplayName {
            get {
                return ResourceManager.GetString("NamedElementCollectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collection of Name Type Configuration elements..
        /// </summary>
        internal static string NameTypeConfigurationElementCollectionDescription {
            get {
                return ResourceManager.GetString("NameTypeConfigurationElementCollectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Type Configuration Element Collection.
        /// </summary>
        internal static string NameTypeConfigurationElementCollectionDisplayName {
            get {
                return ResourceManager.GetString("NameTypeConfigurationElementCollectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A configuration element in a collection that contains both a type and a name..
        /// </summary>
        internal static string NameTypeConfigurationElementDescription {
            get {
                return ResourceManager.GetString("NameTypeConfigurationElementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Type Configuration Element.
        /// </summary>
        internal static string NameTypeConfigurationElementDisplayName {
            get {
                return ResourceManager.GetString("NameTypeConfigurationElementDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Name Type Configuration Element..
        /// </summary>
        internal static string NameTypeConfigurationElementNameDescription {
            get {
                return ResourceManager.GetString("NameTypeConfigurationElementNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameTypeConfigurationElementNameDisplayName {
            get {
                return ResourceManager.GetString("NameTypeConfigurationElementNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified type name of the Name Type Configuration Element..
        /// </summary>
        internal static string NameTypeConfigurationElementTypeNameDescription {
            get {
                return ResourceManager.GetString("NameTypeConfigurationElementTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name.
        /// </summary>
        internal static string NameTypeConfigurationElementTypeNameDisplayName {
            get {
                return ResourceManager.GetString("NameTypeConfigurationElementTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A base class from which all implementations of polymorphic configuration collections derive..
        /// </summary>
        internal static string PolymorphicConfigurationElementCollectionDescription {
            get {
                return ResourceManager.GetString("PolymorphicConfigurationElementCollectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polymorphic Configuration Element Collection.
        /// </summary>
        internal static string PolymorphicConfigurationElementCollectionDisplayName {
            get {
                return ResourceManager.GetString("PolymorphicConfigurationElementCollectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A redirected section for the application configuration. 
        ///Each section of the configuration can be loaded from a different configuration source if required. 
        ///Each Redirected Section configured in this list will override the same entire section in 
        ///the default Configuration Source..
        /// </summary>
        internal static string RedirectedSectionElementDescription {
            get {
                return ResourceManager.GetString("RedirectedSectionElementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirected Section.
        /// </summary>
        internal static string RedirectedSectionElementDisplayName {
            get {
                return ResourceManager.GetString("RedirectedSectionElementDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Redirected Section..
        /// </summary>
        internal static string RedirectedSectionElementNameDescription {
            get {
                return ResourceManager.GetString("RedirectedSectionElementNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string RedirectedSectionElementNameDisplayName {
            get {
                return ResourceManager.GetString("RedirectedSectionElementNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Configuration Source that will handle the redirected section. 
        ///Must be one of the Configuration Sources defined for the application..
        /// </summary>
        internal static string RedirectedSectionElementSourceNameDescription {
            get {
                return ResourceManager.GetString("RedirectedSectionElementSourceNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Source.
        /// </summary>
        internal static string RedirectedSectionElementSourceNameDisplayName {
            get {
                return ResourceManager.GetString("RedirectedSectionElementSourceNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents a configuration section that can be serialized and deserialized to XML..
        /// </summary>
        internal static string SerializableConfigurationSectionDescription {
            get {
                return ResourceManager.GetString("SerializableConfigurationSectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serializable Configuration Section.
        /// </summary>
        internal static string SerializableConfigurationSectionDisplayName {
            get {
                return ResourceManager.GetString("SerializableConfigurationSectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A configuration source that reads configuration data from the default configuration file. 
        ///Typically this is App.config or Web.config, depending on the application type..
        /// </summary>
        internal static string SystemConfigurationSourceElementDescription {
            get {
                return ResourceManager.GetString("SystemConfigurationSourceElementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Configuration Source.
        /// </summary>
        internal static string SystemConfigurationSourceElementDisplayName {
            get {
                return ResourceManager.GetString("SystemConfigurationSourceElementDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the System Configuration Source..
        /// </summary>
        internal static string SystemConfigurationSourceElementNameDescription {
            get {
                return ResourceManager.GetString("SystemConfigurationSourceElementNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SystemConfigurationSourceElementNameDisplayName {
            get {
                return ResourceManager.GetString("SystemConfigurationSourceElementNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fully qualified type name of the System Configuration Source..
        /// </summary>
        internal static string SystemConfigurationSourceElementTypeNameDescription {
            get {
                return ResourceManager.GetString("SystemConfigurationSourceElementTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string SystemConfigurationSourceElementTypeNameDisplayName {
            get {
                return ResourceManager.GetString("SystemConfigurationSourceElementTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collection of Type Registration Provider elements..
        /// </summary>
        internal static string TypeRegistrationProviderElementCollectionDescription {
            get {
                return ResourceManager.GetString("TypeRegistrationProviderElementCollectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Registration Provider Element Collection.
        /// </summary>
        internal static string TypeRegistrationProviderElementCollectionDisplayName {
            get {
                return ResourceManager.GetString("TypeRegistrationProviderElementCollectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A provider for registering types..
        /// </summary>
        internal static string TypeRegistrationProviderElementDescription {
            get {
                return ResourceManager.GetString("TypeRegistrationProviderElementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Registration Provider Element.
        /// </summary>
        internal static string TypeRegistrationProviderElementDisplayName {
            get {
                return ResourceManager.GetString("TypeRegistrationProviderElementDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the Type Registration Provider Element..
        /// </summary>
        internal static string TypeRegistrationProviderElementNameDescription {
            get {
                return ResourceManager.GetString("TypeRegistrationProviderElementNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TypeRegistrationProviderElementNameDisplayName {
            get {
                return ResourceManager.GetString("TypeRegistrationProviderElementNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the type that implements the Type Registration Provider Element..
        /// </summary>
        internal static string TypeRegistrationProviderElementProviderTypeNameDescription {
            get {
                return ResourceManager.GetString("TypeRegistrationProviderElementProviderTypeNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Type Name.
        /// </summary>
        internal static string TypeRegistrationProviderElementProviderTypeNameDisplayName {
            get {
                return ResourceManager.GetString("TypeRegistrationProviderElementProviderTypeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the configuration section within the configuration file..
        /// </summary>
        internal static string TypeRegistrationProviderElementSectionNameDescription {
            get {
                return ResourceManager.GetString("TypeRegistrationProviderElementSectionNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Name.
        /// </summary>
        internal static string TypeRegistrationProviderElementSectionNameDisplayName {
            get {
                return ResourceManager.GetString("TypeRegistrationProviderElementSectionNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The section of the configuration that specifies the Type Registration Providers for the application..
        /// </summary>
        internal static string TypeRegistrationProvidersConfigurationSectionDescription {
            get {
                return ResourceManager.GetString("TypeRegistrationProvidersConfigurationSectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Registration Providers Configuration Section.
        /// </summary>
        internal static string TypeRegistrationProvidersConfigurationSectionDisplayName {
            get {
                return ResourceManager.GetString("TypeRegistrationProvidersConfigurationSectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collection of Type Registration providers..
        /// </summary>
        internal static string TypeRegistrationProvidersConfigurationSectionTypeRegistrationProvidersDescription {
            get {
                return ResourceManager.GetString("TypeRegistrationProvidersConfigurationSectionTypeRegistrationProvidersDescription" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Registration Providers.
        /// </summary>
        internal static string TypeRegistrationProvidersConfigurationSectionTypeRegistrationProvidersDisplayName {
            get {
                return ResourceManager.GetString("TypeRegistrationProvidersConfigurationSectionTypeRegistrationProvidersDisplayName" +
                        "", resourceCulture);
            }
        }
    }
}
