//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transformalize.Libs.EnterpriseLibrary.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Transformalize.Libs.EnterpriseLibrary.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create design source for rootSource other than DesignConfigurationSource..
        /// </summary>
        internal static string CannotCreateDesignSource {
            get {
                return ResourceManager.GetString("CannotCreateDesignSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; defined in the &apos;{1}&apos; configuration source is invalid.
        /// </summary>
        internal static string ConfigurationSourceInvalidTypeErrorMessage {
            get {
                return ResourceManager.GetString("ConfigurationSourceInvalidTypeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exception that occured was: {0}.
        /// </summary>
        internal static string EventLogEntryExceptionTemplate {
            get {
                return ResourceManager.GetString("EventLogEntryExceptionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in application {0} in the {1}..
        /// </summary>
        internal static string EventLogEntryHeaderTemplate {
            get {
                return ResourceManager.GetString("EventLogEntryHeaderTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not derive from IDictionary..
        /// </summary>
        internal static string ExceptionArgumentShouldDeriveFromIDictionary {
            get {
                return ResourceManager.GetString("ExceptionArgumentShouldDeriveFromIDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not derive from IList..
        /// </summary>
        internal static string ExceptionArgumentShouldDeriveFromIList {
            get {
                return ResourceManager.GetString("ExceptionArgumentShouldDeriveFromIList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [Assembler] attribute is not set in the configuration object type {0}..
        /// </summary>
        internal static string ExceptionAssemblerAttributeNotSet {
            get {
                return ResourceManager.GetString("ExceptionAssemblerAttributeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembler configured for type {0} has type {2} which is not compatible with type {1}..
        /// </summary>
        internal static string ExceptionAssemblerTypeNotCompatible {
            get {
                return ResourceManager.GetString("ExceptionAssemblerTypeNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base ConfigurationSourceElement configuration type can not be used as a concrete configuration element..
        /// </summary>
        internal static string ExceptionBaseConfigurationSourceElementIsInvalid {
            get {
                return ResourceManager.GetString("ExceptionBaseConfigurationSourceElementIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add new paramters after Finish() or Dispose()..
        /// </summary>
        internal static string ExceptionCannotAddParametersAfterDispose {
            get {
                return ResourceManager.GetString("ExceptionCannotAddParametersAfterDispose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AssemblyQualifiedTypeNameConverter can only convert values of type &apos;{0}&apos;..
        /// </summary>
        internal static string ExceptionCanNotConvertType {
            get {
                return ResourceManager.GetString("ExceptionCanNotConvertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builder has already added policies..
        /// </summary>
        internal static string ExceptionCannotFinish {
            get {
                return ResourceManager.GetString("ExceptionCannotFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The section {0} could not be saved because the file does not exist..
        /// </summary>
        internal static string ExceptionConfigurationFileNotFound {
            get {
                return ResourceManager.GetString("ExceptionConfigurationFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file {0} could not be found..
        /// </summary>
        internal static string ExceptionConfigurationLoadFileNotFound {
            get {
                return ResourceManager.GetString("ExceptionConfigurationLoadFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration object for type &apos;{0}&apos; with name &apos;{1}&apos; has type &apos;{2}&apos; which is does not implement ICustomProviderData..
        /// </summary>
        internal static string ExceptionConfigurationObjectIsNotCustomProviderData {
            get {
                return ResourceManager.GetString("ExceptionConfigurationObjectIsNotCustomProviderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The concrete type for polymorphic object named &apos;{1}&apos; in hierarchy {2} is not defined in configuration object {0}..
        /// </summary>
        internal static string ExceptionConfigurationObjectWithTypeDoesNotHaveTypeSet {
            get {
                return ResourceManager.GetString("ExceptionConfigurationObjectWithTypeDoesNotHaveTypeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration section &apos;{0}&apos; specifies Source &apos;{1}&apos;, which is not declared in the configuration sources section..
        /// </summary>
        internal static string ExceptionConfigurationSectionPointsToNonExistingSource {
            get {
                return ResourceManager.GetString("ExceptionConfigurationSectionPointsToNonExistingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A configuration source named &apos;{0}&apos; was not found in the {1} section..
        /// </summary>
        internal static string ExceptionConfigurationSourceNotFound {
            get {
                return ResourceManager.GetString("ExceptionConfigurationSourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration source section is not found in the application configuration file..
        /// </summary>
        internal static string ExceptionConfigurationSourceSectionNotFound {
            get {
                return ResourceManager.GetString("ExceptionConfigurationSourceSectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required &quot;ContainerPolicyCreatorAttribute&quot; is not present in the supplied type &quot;{0}&quot;..
        /// </summary>
        internal static string ExceptionContainerPolicyCreatorAttributeNotPresent {
            get {
                return ResourceManager.GetString("ExceptionContainerPolicyCreatorAttributeNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [CustomFactory] attribute was not found on type {0} while processing request for id &apos;{1}&apos;..
        /// </summary>
        internal static string ExceptionCustomFactoryAttributeNotFound {
            get {
                return ResourceManager.GetString("ExceptionCustomFactoryAttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; specified as a custom provider does not have the required public constructor with a single NameValueCollection parameter..
        /// </summary>
        internal static string ExceptionCustomProviderTypeDoesNotHaveTheRequiredConstructor {
            get {
                return ResourceManager.GetString("ExceptionCustomProviderTypeDoesNotHaveTheRequiredConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error raising an event in .
        /// </summary>
        internal static string ExceptionEventRaisingFailed {
            get {
                return ResourceManager.GetString("ExceptionEventRaisingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method with signature {0} is not a valid factory method to build type {1}..
        /// </summary>
        internal static string ExceptionFactoryMethodHasInvalidReturnType {
            get {
                return ResourceManager.GetString("ExceptionFactoryMethodHasInvalidReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot merge the configuration element.
        ///The local elements type &apos;{0}&apos; is  incompatible with the parent elements type &apos;{1}&apos;..
        /// </summary>
        internal static string ExceptionIncompaitbleMergeElementType {
            get {
                return ResourceManager.GetString("ExceptionIncompaitbleMergeElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; cannot be resolved. Please verify the spelling is correct or that the full type name is provided..
        /// </summary>
        internal static string ExceptionInvalidType {
            get {
                return ResourceManager.GetString("ExceptionInvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied configuration object has type &apos;{0}&apos;, which is not a descendant of &apos;NameTypeConfigurationElement&apos; as required..
        /// </summary>
        internal static string ExceptionMustBeNameTypeConfigurationElement {
            get {
                return ResourceManager.GetString("ExceptionMustBeNameTypeConfigurationElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required zero argument constructor is not available for the supplied type &quot;{0}&quot;..
        /// </summary>
        internal static string ExceptionMustHaveNoArgsConstructor {
            get {
                return ResourceManager.GetString("ExceptionMustHaveNoArgsConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required interface &quot;IContainerPolicyCreator&quot; is not implemented by the supplied type &quot;{0}&quot;..
        /// </summary>
        internal static string ExceptionMustImplementIContainerPolicyCreator {
            get {
                return ResourceManager.GetString("ExceptionMustImplementIContainerPolicyCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration could not be found for name &apos;{0}&apos; in factory {1}..
        /// </summary>
        internal static string ExceptionNamedConfigurationNotFound {
            get {
                return ResourceManager.GetString("ExceptionNamedConfigurationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} does not contain the ConfigurationElementTypeAttribute..
        /// </summary>
        internal static string ExceptionNoConfigurationElementAttribute {
            get {
                return ResourceManager.GetString("ExceptionNoConfigurationElementAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No policy specifying the configuration source for the container has been set. The EnterpriseLibraryCoreExtension is probably missing..
        /// </summary>
        internal static string ExceptionNoConfigurationObjectPolicySet {
            get {
                return ResourceManager.GetString("ExceptionNoConfigurationObjectPolicySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No public constructor with {1} arguments was found for type &quot;{0}&quot;..
        /// </summary>
        internal static string ExceptionNoMatchingConstructorFound {
            get {
                return ResourceManager.GetString("ExceptionNoMatchingConstructorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} does not have a public method annotated as an injection target as required by the use of injection..
        /// </summary>
        internal static string ExceptionNoMethodAnnotatedForInjectionFound {
            get {
                return ResourceManager.GetString("ExceptionNoMethodAnnotatedForInjectionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} does not have a static method with a TargetConstructorAttribuite suitable to create an object of type {1}..
        /// </summary>
        internal static string ExceptionNoSuitableFactoryMethodFound {
            get {
                return ResourceManager.GetString("ExceptionNoSuitableFactoryMethodFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type attribute does not exist on the element {0}..
        /// </summary>
        internal static string ExceptionNoTypeAttribute {
            get {
                return ResourceManager.GetString("ExceptionNoTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; for injection target &apos;{1}&apos; in type &apos;{2}&apos; is missing the injection interpretation attribute..
        /// </summary>
        internal static string ExceptionParameterNotAnnotatedForInjection {
            get {
                return ResourceManager.GetString("ExceptionParameterNotAnnotatedForInjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The performance counter &apos;{0}&apos; in category &apos;{1}&apos; is redefined in type {2} with a different configuration..
        /// </summary>
        internal static string ExceptionPerformanceCounterRedefined {
            get {
                return ResourceManager.GetString("ExceptionPerformanceCounterRedefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to continue working with a PolicyBuilder after the policies have been added to a policy list for type &apos;{1}&apos; with key &apos;{0}&apos;..
        /// </summary>
        internal static string ExceptionPolicyBuilderFinished {
            get {
                return ResourceManager.GetString("ExceptionPolicyBuilderFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified policies cannot be added: a property policy mapping is still taking place..
        /// </summary>
        internal static string ExceptionPolicyBuilderStillWaitingForPropertyPolicy {
            get {
                return ResourceManager.GetString("ExceptionPolicyBuilderStillWaitingForPropertyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied expression is not a valid property access expression: &apos;{0}&apos;..
        /// </summary>
        internal static string ExceptionPropertyAccessExpressionNotPropertyAccess {
            get {
                return ResourceManager.GetString("ExceptionPropertyAccessExpressionNotPropertyAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e {2}..
        /// </summary>
        internal static string ExceptionPropertyNotFound {
            get {
                return ResourceManager.GetString("ExceptionPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the redirected section {0} in the specified configuration source {1}..
        /// </summary>
        internal static string ExceptionRedirectedConfigurationSectionNotFound {
            get {
                return ResourceManager.GetString("ExceptionRedirectedConfigurationSectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service type of {0} is not compatible with supplied expression type of {1}.
        /// </summary>
        internal static string ExceptionRegistrationServiceTypeIsNotCompatible {
            get {
                return ResourceManager.GetString("ExceptionRegistrationServiceTypeIsNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lambda expression must construct a new instance of a type..
        /// </summary>
        internal static string ExceptionRegistrationTypeExpressionMustBeNewLambda {
            get {
                return ResourceManager.GetString("ExceptionRegistrationTypeExpressionMustBeNewLambda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} does not contain the ConfigurationDataRetrievalAttribute required to resolve named references..
        /// </summary>
        internal static string ExceptionRetrievalAttributeNotFound {
            get {
                return ResourceManager.GetString("ExceptionRetrievalAttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method must be overriden by subclass..
        /// </summary>
        internal static string ExceptionShouldBeImplementedBySubclass {
            get {
                return ResourceManager.GetString("ExceptionShouldBeImplementedBySubclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve parameter value. The property {0} does not exist for type {1}..
        /// </summary>
        internal static string ExceptionSourcePropertyDoesNotExist {
            get {
                return ResourceManager.GetString("ExceptionSourcePropertyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument cannot be empty..
        /// </summary>
        internal static string ExceptionStringEmpty {
            get {
                return ResourceManager.GetString("ExceptionStringEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value can not be null or string or empty..
        /// </summary>
        internal static string ExceptionStringNullOrEmpty {
            get {
                return ResourceManager.GetString("ExceptionStringNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A creation expression must be a constructor call, but the supplied expression was &apos;{0}&apos;..
        /// </summary>
        internal static string ExceptionSuppliedCreationExpressionIsNotNewExpression {
            get {
                return ResourceManager.GetString("ExceptionSuppliedCreationExpressionIsNotNewExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system configuration source is not defined in the configuration file..
        /// </summary>
        internal static string ExceptionSystemSourceNotDefined {
            get {
                return ResourceManager.GetString("ExceptionSystemSourceNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration object for default provider named &apos;{0}&apos; for type &apos;{1}&apos; was not found in the supplied list..
        /// </summary>
        internal static string ExceptionTheSpecifiedDefaultProviderDoesNotExistInConfiguration {
            get {
                return ResourceManager.GetString("ExceptionTheSpecifiedDefaultProviderDoesNotExistInConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} from configuration could not be created..
        /// </summary>
        internal static string ExceptionTypeCouldNotBeCreated {
            get {
                return ResourceManager.GetString("ExceptionTypeCouldNotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type does not provide a constructor taking a single parameter type of NameValueCollection.
        /// </summary>
        internal static string ExceptionTypeDoesNotProvideCorrectConstructor {
            get {
                return ResourceManager.GetString("ExceptionTypeDoesNotProvideCorrectConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type must be derived from &apos;{0}&apos;..
        /// </summary>
        internal static string ExceptionTypeMustDeriveFromType {
            get {
                return ResourceManager.GetString("ExceptionTypeMustDeriveFromType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type must implement interface &apos;{0}&apos;..
        /// </summary>
        internal static string ExceptionTypeMustImplementInterface {
            get {
                return ResourceManager.GetString("ExceptionTypeMustImplementInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not an implementation of ICustomFactory for CustomFactoryAttribute..
        /// </summary>
        internal static string ExceptionTypeNotCustomFactory {
            get {
                return ResourceManager.GetString("ExceptionTypeNotCustomFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not an implementation of IConfigurationNameMapper for ConfigurationNameMapperAttribute..
        /// </summary>
        internal static string ExceptionTypeNotNameMapper {
            get {
                return ResourceManager.GetString("ExceptionTypeNotNameMapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not an implementation of IConfigurationDataRetriever for ConfigurationDataRetrievalAttribute..
        /// </summary>
        internal static string ExceptionTypeNotRetriever {
            get {
                return ResourceManager.GetString("ExceptionTypeNotRetriever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default policy creation failed: The properties in the supplied configuration object of type {0} cannot be matched to any constructor on type {1}..
        /// </summary>
        internal static string ExceptionUnableToMatchConstructorToConfigurationObject {
            get {
                return ResourceManager.GetString("ExceptionUnableToMatchConstructorToConfigurationObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expected type &apos;{0}&apos; was not provided..
        /// </summary>
        internal static string ExceptionUnexpectedType {
            get {
                return ResourceManager.GetString("ExceptionUnexpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An call to an unknown method named &apos;{0}&apos; in the Resolve class was found in the supplied argument expression: &apos;{1}&apos;. Cannot create policies for this expression..
        /// </summary>
        internal static string ExceptionUnknownResolveMethod {
            get {
                return ResourceManager.GetString("ExceptionUnknownResolveMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized Container marker method..
        /// </summary>
        internal static string ExceptionUnrecognizedContainerMarkerMethod {
            get {
                return ResourceManager.GetString("ExceptionUnrecognizedContainerMarkerMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized DependencyParameter type: {0}.
        /// </summary>
        internal static string ExceptionUnrecognizedDependencyParameterType {
            get {
                return ResourceManager.GetString("ExceptionUnrecognizedDependencyParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The initialization expression for property {0} is not supported: only simple bindings are supported..
        /// </summary>
        internal static string ExceptionUnsupportedBindingExpressionType {
            get {
                return ResourceManager.GetString("ExceptionUnsupportedBindingExpressionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Configuration Source.
        /// </summary>
        internal static string FileConfigurationSourceName {
            get {
                return ResourceManager.GetString("FileConfigurationSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Configuration Source.
        /// </summary>
        internal static string SystemConfigurationSourceName {
            get {
                return ResourceManager.GetString("SystemConfigurationSourceName", resourceCulture);
            }
        }
    }
}
