<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Transformalize.Providers.Json</RootNamespace>
    <AssemblyName>Transformalize.Provider.Json</AssemblyName>
    <Version>1.5.0</Version>
    <FileVersion>1.5.0</FileVersion>
    <AssemblyVersion>1.5.0</AssemblyVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="10.0.8" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../Transformalize/Transformalize.csproj" />
  </ItemGroup>
</Project>